# Use root/passWd123 as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passWd123
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: passWd123
      ME_CONFIG_MONGODB_URL: mongodb://root:passWd123@mongo:27017/

volumes:
  mongodata:
    driver: local
